# ==========================================
# BASE DE DATOS EN MEMORIA (H2) - APAGADA
# ==========================================
# spring.datasource.url=jdbc:h2:mem:staffsync_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

# ==========================================
# BASE DE DATOS REAL (POSTGRESQL EN PODMAN)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/staffsync_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# EVITAR CHOQUE DE PUERTOS (Opcional pero recomendado)
# ==========================================
# Como el contenedor ya está usando el 8080, le decimos a tu VS Code que use el 8081
