# ==========================================
# 1. CONFIGURACIÓN GENERAL DEL SERVIDOR
# ==========================================
# Puerto donde correrá nuestra API (por defecto es 8080)
server.port=8080
# Nombre de nuestro microservicio
spring.application.name=staffsync-service

# ==========================================
# 2. BASE DE DATOS EN MEMORIA (H2) - ACTIVA
# ==========================================
# URL de conexión (crea una BD temporal en la RAM llamada staffsync_db)
spring.datasource.url=jdbc:h2:mem:staffsync_db
# El motor o "chofer" que sabe cómo hablar con H2
spring.datasource.driverClassName=org.h2.Driver
# Usuario por defecto de H2
spring.datasource.username=sa
# Contraseña por defecto (puede ir vacía)
spring.datasource.password=password
# Habilita una interfaz gráfica en el navegador para ver las tablas en http://localhost:8080/h2-console
spring.h2.console.enabled=true
# El "diccionario" de SQL que usa Hibernate para hablar con H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================================
# 3. BASE DE DATOS REAL (POSTGRESQL) - INACTIVA
# ==========================================

# spring.datasource.url=jdbc:postgresql://localhost:5432/staffsync_db
# spring.datasource.username=postgres
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 4. CONFIGURACIÓN DE HIBERNATE / JPA (MÁGIA DE TABLAS)
# ==========================================
# 'update': Lee tus Entidades (@Entity) y crea o actualiza las tablas automáticamente sin borrar los datos.
# (En producción real se usa 'validate' o 'none', pero para desarrollo 'update' es perfecto).
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola (terminal) las sentencias SQL reales que Spring hace por debajo.
# Súper útil para aprender y ver qué consultas a la base de datos está haciendo tu aplicación.
spring.jpa.show-sql=true

# Da un formato bonito y legible al SQL en la consola, en lugar de imprimirlo todo en una sola línea.
spring.jpa.properties.hibernate.format_sql=true